### ISSUE TITLE
Problem installing wfmash with conda

### ISSUE THREAD

**Issue by VLoegler** [waveygang/wfmash#147]
I tried to install wfmash with conda with these commands:

```
$ conda create -n wfmashEnv
$ conda activate wfmashEnv
$ conda install -c bioconda wfmash
```

The installation ended well, but when I try to use wfmash, I have this error:

```
$ wfmash
wfmash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
```

In my folder anaconda3/envs/wfmashEnv/lib/, I have the file libgsl.so.27 but not the file libgsl.so.25. 
How can I solve this problem ?

**Comment by xiekunwhy** [comment]
+1

**Comment by xiekunwhy** [comment]
wfmash required libgsl.so.27 but load libgsl.so.25, 
cd wfmashEnv/lib
ln -s libgsl.so.27 libgsl.so.25
may solve the problem

**Comment by ekg** [comment]
We should probably cut a new release to try to balance this out.

**Comment by AndreaGuarracino** [comment]
@xiekunwhy, do you have the same problem with wfmash 0.10.0 on [bioconda](https://anaconda.org/bioconda/wfmash)?

**Comment by xiekunwhy** [comment]
@AndreaGuarracino , everything goes well when I installing wfmash 0.10.0.

**Comment by AndreaGuarracino** [comment]
@xiekunwhy, thank you for the feedback!

**Comment by acontrerasg** [comment]
> ln -s libgsl.so.27 libgsl.so.25

This worked for me.
