### ISSUE TITLE
output bam file?

### ISSUE THREAD

**Issue by jianshu93** [waveygang/wfmash#168]
Hello Team,

I am wondering whether wfmash can also generate bam file similar to that of minimap2. so that we can also use it as an reads mapper for many other applications.

thanks,

Jianshu

**Comment by AndreaGuarracino** [comment]
Hi @jianshu93,
have you already played with the `--sam-format` option? What is missing?

**Comment by jianshu93** [comment]
oh thanks！I will close this issue then and come back with more comparisons with minimap2.

Thanks，
Jianshu
