### ISSUE TITLE
wfmash gets stuck (v0.9.1-3-gc5882a1: Mutamento)

### ISSUE THREAD

**Issue by piosierra** [waveygang/wfmash#173]
Running pggb with parameters -t 8 -p 85 -s 5000 -n 2 -U -v -L -k 21, that I have used correctly without problems before, wfmash gets sucked and shows no progress after several hours after step:

[wfmash::skch::Map::mapQuery] mapped 50.00% @ 9.47e+07 bp/s elapsed: 00:00:00:02
 remain: 00:00:00:02

This is happening simultaneously in four jobs trying to align 4 different pairs of segments. Each couple size compressed is around 100MB.

No error appears. The process simply does not proceed from that step, nor any file in the output folder has been updated for hours.

Any idea what might be the issue?

Thanks.

**Comment by AndreaGuarracino** [comment]
Hi @piosierra, I think this might be related to the mapping chaining that happens in the first part of `wfmash`. That's quite aggressive (and expensive) right now. Do you think you can share a subset of your data that trigger this "slowness"?

**Comment by piosierra** [comment]
Sorry Andrea, I forgot to close this. I increased the allowed time and indeed it was able to finish the job. It was just more than I was used to. The data was chr1 of two cetaceans. ~112 MB bgziped

[wfmash::skch::Map::mapQuery] mapped  0.00% @ 0.00e+00 bp/s elapsed: 00:00:00:00 remain: 00:00:00:00
[wfmash::skch::Map::mapQuery] mapped 24.39% @ 6.15e+07 bp/s elapsed: 00:00:00:01 remain: 00:00:00:04
[wfmash::skch::Map::mapQuery] mapped 50.00% @ 9.46e+07 bp/s elapsed: 00:00:00:02 remain: 00:00:00:02
[wfmash::skch::Map::mapQuery] mapped 74.39% @ 1.33e+04 bp/s elapsed: 00:05:53:55 remain: 00:02:01:51
[wfmash::skch::Map::mapQuery] mapped 100.00% @ 1.73e+04 bp/s elapsed: 00:06:05:17 remain: 00:00:00:00
