### ISSUE TITLE
return 1.0d ?

### ISSUE THREAD

**Issue by NullModel** [waveygang/wfmash#226]
What types of constants are this in the code:

`wfmash/src/common/wflign/deps/atomic_image.cpp:95:39: error: invalid suffix 'd' on floating constant
double u_rfpart(double x) { return 1.0d - u_fpart(x); }
`

`gcc -v
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
`

**Comment by AndreaGuarracino** [comment]
Following #232's tips, I've removed those suffixes on float constants. This should improve `clang` compatibility.
