### ISSUE TITLE
invalid 2 field records introduced after inversion patching

### ISSUE THREAD

**Issue by ASLeonard** [waveygang/wfmash#263]
I was rerunning alignments with the new version, and something seems to incorrectly be triggering a *newline* during the record writing, producing an alignment record of just "pt:Z:true		iv:Z:false".

This happens rarely (3 chromosomes out of 29, and 2/1/3 times for those chromosomes), but kills seqwish with an error related to an invalid line.
```
[seqwish::alignments] 8.006 processing alignments
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoull
Aborted
```

Every time the errored lines have "pt:Z:true		iv:Z:false", but there are other lines with "pt:Z:true		iv:Z:false" that are valid (i.e. have 18 fields per alignment). There was also no obvious pattern about the preceding line that would trigger this (but that may irrelevant due to multithreading order).

This is with commit 13882fe. The input file is 306 Mb, so can share that if needed to debug this.

Best,
Alex

**Comment by ekg** [comment]
Thanks for the heads up! I'll try to find an example.

Il ven 9 ago 2024, 15:10 Alex Leonard ***@***.***> ha scritto:

**Comment by ASLeonard** [comment]
I retested one of the failing chromosomes with 087ada0 from #264 and the output correctly had records with only 16/18 fields, so the error seems to be fixed.

**Comment by ekg** [comment]
Thanks for checking this! I can merge #264 and close this issue.
